// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  name: __t.string(),
  isOnline: __t.bool().name("is_online"),
  lastSeen: __t.timestamp().name("last_seen"),
  xp: __t.u64(),
  level: __t.u32(),
  loginStreak: __t.u32().name("login_streak"),
  longestStreak: __t.u32().name("longest_streak"),
  lastLoginDay: __t.u64().name("last_login_day"),
  totalWins: __t.u32().name("total_wins"),
  totalLosses: __t.u32().name("total_losses"),
  totalRoundsPlayed: __t.u32().name("total_rounds_played"),
  isAdmin: __t.option(__t.bool()).name("is_admin"),
});
