// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  code: __t.string(),
  hostIdentity: __t.identity().name("host_identity"),
  status: __t.string(),
  seed: __t.u64(),
  mapType: __t.string().name("map_type"),
  targetScore: __t.u32().name("target_score"),
  roundLimit: __t.u32().name("round_limit"),
  turnDurationMode: __t.option(__t.string()).name("turn_duration_mode"),
  createdAt: __t.timestamp().name("created_at"),
});
