// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roomId: __t.u64().name("room_id"),
  identity: __t.identity(),
  slotIndex: __t.u32().name("slot_index"),
  teamIndex: __t.option(__t.u32()).name("team_index"),
  mobileType: __t.string().name("mobile_type"),
  isReady: __t.bool().name("is_ready"),
  joinedAt: __t.timestamp().name("joined_at"),
});
