// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roundId: __t.u64().name("round_id"),
  playerIdentity: __t.identity().name("player_identity"),
  damageDealt: __t.u32().name("damage_dealt"),
  shotsFired: __t.u32().name("shots_fired"),
  directHits: __t.u32().name("direct_hits"),
  xpAwarded: __t.u32().name("xp_awarded"),
});
