// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AppSetting = __t.object("AppSetting", {
  key: __t.string(),
  value: __t.string(),
  updatedBy: __t.option(__t.identity()),
  updatedAt: __t.timestamp(),
});
export type AppSetting = __Infer<typeof AppSetting>;

export const ChatMessage = __t.object("ChatMessage", {
  id: __t.u64(),
  roomId: __t.u64(),
  senderIdentity: __t.identity(),
  message: __t.string(),
  createdAt: __t.timestamp(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const Credential = __t.object("Credential", {
  username: __t.string(),
  identity: __t.identity(),
  encryptedToken: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Credential = __Infer<typeof Credential>;

export const FriendRequest = __t.object("FriendRequest", {
  id: __t.u64(),
  requesterIdentity: __t.identity(),
  recipientIdentity: __t.identity(),
  get status() {
    return RequestStatus;
  },
  createdAt: __t.timestamp(),
  resolvedAt: __t.option(__t.timestamp()),
});
export type FriendRequest = __Infer<typeof FriendRequest>;

export const Friendship = __t.object("Friendship", {
  id: __t.u64(),
  ownerIdentity: __t.identity(),
  buddyIdentity: __t.identity(),
  createdAt: __t.timestamp(),
});
export type Friendship = __Infer<typeof Friendship>;

export const LobbyChatMessage = __t.object("LobbyChatMessage", {
  id: __t.u64(),
  channel: __t.u32(),
  senderIdentity: __t.identity(),
  message: __t.string(),
  createdAt: __t.timestamp(),
});
export type LobbyChatMessage = __Infer<typeof LobbyChatMessage>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  displayNameSetAt: __t.option(__t.timestamp()),
  isOnline: __t.bool(),
  lastSeen: __t.timestamp(),
  xp: __t.u64(),
  level: __t.u32(),
  loginStreak: __t.u32(),
  longestStreak: __t.u32(),
  lastLoginDay: __t.u64(),
  totalWins: __t.u32(),
  totalLosses: __t.u32(),
  totalRoundsPlayed: __t.u32(),
  isAdmin: __t.option(__t.bool()),
});
export type Player = __Infer<typeof Player>;

// The tagged union or sum type for the algebraic type `RequestStatus`.
export const RequestStatus = __t.enum("RequestStatus", {
  Pending: __t.unit(),
  Accepted: __t.unit(),
  Declined: __t.unit(),
});
export type RequestStatus = __Infer<typeof RequestStatus>;

export const Room = __t.object("Room", {
  id: __t.u64(),
  code: __t.string(),
  hostIdentity: __t.identity(),
  status: __t.string(),
  seed: __t.u64(),
  mapType: __t.string(),
  targetScore: __t.u32(),
  roundLimit: __t.u32(),
  createdAt: __t.timestamp(),
});
export type Room = __Infer<typeof Room>;

export const RoomInvite = __t.object("RoomInvite", {
  id: __t.u64(),
  roomId: __t.u64(),
  requesterIdentity: __t.identity(),
  recipientIdentity: __t.identity(),
  get status() {
    return RequestStatus;
  },
  createdAt: __t.timestamp(),
  resolvedAt: __t.option(__t.timestamp()),
});
export type RoomInvite = __Infer<typeof RoomInvite>;

export const RoomMember = __t.object("RoomMember", {
  id: __t.u64(),
  roomId: __t.u64(),
  identity: __t.identity(),
  slotIndex: __t.u32(),
  teamIndex: __t.option(__t.u32()),
  mobileType: __t.string(),
  isReady: __t.bool(),
  joinedAt: __t.timestamp(),
});
export type RoomMember = __Infer<typeof RoomMember>;

export const Round = __t.object("Round", {
  id: __t.u64(),
  roomId: __t.u64(),
  seed: __t.u64(),
  status: __t.string(),
  startedAt: __t.timestamp(),
  endedAt: __t.option(__t.timestamp()),
  winnerIdentity: __t.option(__t.identity()),
});
export type Round = __Infer<typeof Round>;

export const RoundEvent = __t.object("RoundEvent", {
  id: __t.u64(),
  roundId: __t.u64(),
  tick: __t.u64(),
  actorIdentity: __t.identity(),
  kind: __t.string(),
  payload: __t.string(),
  createdAt: __t.timestamp(),
});
export type RoundEvent = __Infer<typeof RoundEvent>;

export const RoundStat = __t.object("RoundStat", {
  id: __t.u64(),
  roundId: __t.u64(),
  playerIdentity: __t.identity(),
  damageDealt: __t.u32(),
  shotsFired: __t.u32(),
  directHits: __t.u32(),
  xpAwarded: __t.u32(),
});
export type RoundStat = __Infer<typeof RoundStat>;

