// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  isOnline: __t.bool(),
  lastSeen: __t.timestamp(),
});
export type Player = __Infer<typeof Player>;

export const Room = __t.object("Room", {
  id: __t.u64(),
  code: __t.string(),
  hostIdentity: __t.identity(),
  status: __t.string(),
  seed: __t.u64(),
  createdAt: __t.timestamp(),
});
export type Room = __Infer<typeof Room>;

export const RoomMember = __t.object("RoomMember", {
  id: __t.u64(),
  roomId: __t.u64(),
  identity: __t.identity(),
  joinedAt: __t.timestamp(),
});
export type RoomMember = __Infer<typeof RoomMember>;

export const Round = __t.object("Round", {
  id: __t.u64(),
  roomId: __t.u64(),
  seed: __t.u64(),
  status: __t.string(),
  startedAt: __t.timestamp(),
  endedAt: __t.option(__t.timestamp()),
  winnerIdentity: __t.option(__t.identity()),
});
export type Round = __Infer<typeof Round>;

export const RoundEvent = __t.object("RoundEvent", {
  id: __t.u64(),
  roundId: __t.u64(),
  tick: __t.u64(),
  actorIdentity: __t.identity(),
  kind: __t.string(),
  payload: __t.string(),
  createdAt: __t.timestamp(),
});
export type RoundEvent = __Infer<typeof RoundEvent>;

