// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateRoomReducer from "../create_room_reducer";
import EndRoundReducer from "../end_round_reducer";
import JoinRoomByCodeReducer from "../join_room_by_code_reducer";
import LeaveRoomReducer from "../leave_room_reducer";
import RecordRoundEventReducer from "../record_round_event_reducer";
import SetPlayerNameReducer from "../set_player_name_reducer";
import StartRoundReducer from "../start_round_reducer";

export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type EndRoundParams = __Infer<typeof EndRoundReducer>;
export type JoinRoomByCodeParams = __Infer<typeof JoinRoomByCodeReducer>;
export type LeaveRoomParams = __Infer<typeof LeaveRoomReducer>;
export type RecordRoundEventParams = __Infer<typeof RecordRoundEventReducer>;
export type SetPlayerNameParams = __Infer<typeof SetPlayerNameReducer>;
export type StartRoundParams = __Infer<typeof StartRoundReducer>;

